### ISSUE TITLE
Big bug with 75.1.1! no longer detects UTF-8 with no BOM

### ISSUE THREAD

**Issue by alugowski** [sigpwned/chardet4j#49]
I just tried v75.1.1 to try #45, which works great to detect files with a BOM but now it breaks on files that don't have one.

I use the library like `var reader = Chardet.decode(stream, StandardCharsets.UTF_8)` (copy-pasted from the README), and it works great for a variety of input files and encodings with v75.1.0, but with v75.1.1 many files without a BOM do not read correctly. My usecase reads JSON from this reader and the update causes all sorts of validation errors.

Seems it is no longer respecting my default choice of UTF-8 if a BOM is not present.

**Comment by sigpwned** [comment]
Woof! Sorry about that. Big bug indeed.

I was able to reproduce -- thank you for sample code above -- and fix.

I've rolled a new release, v75.1.2, which has been released and should be live in Maven Central in the next few hours.

It includes two new (obviously important) regression tests that test functionality with and without BOMs for `Chardet#detectCharset` and `Charset#decode`: [detectCharsetTest](https://github.com/sigpwned/chardet4j/blob/v75.1.2/src/test/java/com/sigpwned/chardet4j/ChardetTest.java#L225) and  [decodeTest](https://github.com/sigpwned/chardet4j/blob/v75.1.2/src/test/java/com/sigpwned/chardet4j/ChardetTest.java#L296), respectively. Code is linked if you're curious.

Apologies for the churn! Hope it didn't cause too much heartburn.
